export const VI = {
  // Navigation
  'Shop By Category': 'Mua theo danh mục',
  'Search Products': 'Tìm kiếm sầu riêng',
  'Free Shipping': 'Miễn phí vận chuyển',
  'Payment Methods': 'Phương thức thanh toán',
  'Call us': 'Gọi cho chúng tôi',
  'Need advice? Call us': 'Cần tư vấn? Gọi cho chúng tôi',
  'MERN Store': 'Durian Shop',
  'Brands': 'Thương hiệu',
  'Shop': 'Cửa hàng',
  'Welcome': 'Chào mừng',
  'Welcome!': 'Chào mừng!',
  'Dashboard': 'Bảng điều khiển',
  'Sign Out': 'Đăng xuất',
  'Login': 'Đăng nhập',
  'Sign Up': 'Đăng ký',
  'Back To Login': 'Quay lại trang đăng nhập',
  'Login with Google': 'Đăng nhập với Google',
  'Login with Facebook': 'Đăng nhập với Facebook',
  'Or': 'Hoặc',
  'Subscribe to newsletter': 'Đăng ký nhận bản tin',
  'Forgot Password?': 'Quên mật khẩu?',
  'Create an account': 'Tạo một tài khoản',
  
  // Footer
  'Customer Service': 'Dịch vụ khách hàng',
  'Contact Us': 'Liên hệ chúng tôi',
  'Sell With Us': 'Bán cùng chúng tôi',
  'Shipping': 'Vận chuyển',
  'Links': 'Liên kết',
  'Newsletter': 'Bản tin',
  'Account Details': 'Chi tiết tài khoản',
  'Orders': 'Đơn hàng',
  'Account Security': 'Bảo mật tài khoản',
  'Address': 'Địa chỉ',
  'Users': 'Người dùng',
  'Merchants': 'Người bán',
  'Reviews': 'Đánh giá',
  'Wishlist': 'Danh sách yêu thích',
  'WishList': 'Danh sách yêu thích',
  'Support': 'Hỗ trợ',
  
  // Buttons
  'Submit': 'Gửi',
  'Cancel': 'Hủy',
  'Add': 'Thêm',
  'Edit': 'Sửa',
  'Delete': 'Xóa',
  'Save': 'Lưu',
  'Update': 'Cập nhật',
  'Search': 'Tìm kiếm',
  'Continue shopping': 'Tiếp tục mua sắm',
  'Place Order': 'Đặt hàng',
  'Proceed To Checkout': 'Tiến hành thanh toán',
  'Back to orders': 'Quay lại đơn hàng',
  'Cancel Order': 'Hủy đơn hàng',
  'Approve': 'Phê duyệt',
  'Reject': 'Từ chối',
  'Re Approve Review': 'Phê duyệt lại đánh giá',
  
  // Forms
  'Name': 'Tên',
  'Email Address': 'Địa chỉ email',
  'Phone Number': 'Số điện thoại',
  'Password': 'Mật khẩu',
  'Confirm Password': 'Xác nhận mật khẩu',
  'Message': 'Tin nhắn',
  'Title': 'Tiêu đề',
  'Comment': 'Bình luận',
  'Rating': 'Đánh giá',
  'Description': 'Mô tả',
  'Brand': 'Thương hiệu',
  'Business': 'Kinh doanh',
  'Category': 'Danh mục',
  'Categories': 'Danh mục',
  'Products': 'Sản phẩm',
  'Price': 'Giá',
  'Quantity': 'Số lượng',
  'Total': 'Tổng cộng',
  'Status': 'Trạng thái',
  'Active?': 'Hoạt động?',
  'Weight': 'Trọng lượng',
  'Ripeness': 'Độ chín',
  'Origin': 'Xuất xứ',
  
  // Placeholders
  'Your Full Name': 'Họ và tên của bạn',
  'Your Email Address': 'Địa chỉ email của bạn',
  'Your Phone Number': 'Số điện thoại của bạn',
  'Your Business Brand': 'Thương hiệu kinh doanh của bạn',
  'Please Describe Your Business': 'Vui lòng mô tả doanh nghiệp của bạn',
  'Please Describe Your Message': 'Vui lòng mô tả tin nhắn của bạn',
  'Enter Review title': 'Nhập tiêu đề đánh giá',
  'Write Review': 'Viết đánh giá',
  'Type Email, Phone Number, Brand Or Status': 'Nhập Email, SĐT, Thương hiệu hoặc Trạng thái',
  'Brand Name': 'Tên thương hiệu',
  'Brand Description': 'Mô tả thương hiệu',
  'Request date': 'Ngày yêu cầu',
  'Edit Product': 'Chỉnh sửa sản phẩm',
  'Product Name': 'Tên sản phẩm',
  'Product Sku': 'Mã SKU sản phẩm',
  'Product Slug': 'Slug sản phẩm',
  'Product Description': 'Mô tả sản phẩm',
  'Product Quantity': 'Số lượng sản phẩm',
  'Product Price': 'Giá sản phẩm',
  'Select Brand': 'Chọn thương hiệu',
  'Taxable': 'Chịu thuế',
  'Yes': 'Có',
  'No': 'Không',
  'Edit Category': 'Chỉnh sửa danh mục',
  'Category Name': 'Tên danh mục',
  'Category Slug': 'Slug danh mục',
  'Category Description': 'Mô tả danh mục',
  'Select Products': 'Chọn sản phẩm',
  'No category found.': 'Không tìm thấy danh mục.',
  'Edit Brand': 'Chỉnh sửa thương hiệu',
  'Brand Slug': 'Slug thương hiệu',
  'No brand found.': 'Không tìm thấy thương hiệu.',
  'Change Password': 'Đổi mật khẩu',
  'Current Password': 'Mật khẩu hiện tại',
  'New Password': 'Mật khẩu mới',
  'Confirm New Password': 'Xác nhận mật khẩu mới',
  'Add Address': 'Thêm địa chỉ',
  'Edit Address': 'Chỉnh sửa địa chỉ',
  'Set as default': 'Đặt làm mặc định',
  'Default Delivery Address': 'Địa chỉ giao hàng mặc định',
  'City': 'Thành phố',
  'State': 'Tỉnh/Bang',
  'Country': 'Quốc gia',
  'Zip Code': 'Mã bưu điện',
  'No addresses found.': 'Không tìm thấy địa chỉ.',
  'No users found.': 'Không tìm thấy người dùng.',
  'First Name': 'Tên',
  'Last Name': 'Họ',
  'Role': 'Vai trò',
  'Joined': 'Ngày tham gia',
  'User': 'Người dùng',
  'No items found in your wishlist.': 'Không có sản phẩm nào trong danh sách yêu thích.',
  'Review': 'Đánh giá',
  'Date': 'Ngày',
  'Type name, price or status': 'Nhập tên, giá hoặc trạng thái',
  'Order ID': 'Mã đơn hàng',
  'Customer': 'Khách hàng',
  'Total': 'Tổng tiền',
  'Type order number or status': 'Nhập mã đơn hàng hoặc trạng thái',
  'Type user name or email': 'Nhập tên hoặc email người dùng',
  'Type product name or review title': 'Nhập tên sản phẩm hoặc tiêu đề đánh giá',
  'No reviews found': 'Không tìm thấy đánh giá nào',
  'No wishlist found': 'Không tìm thấy danh sách yêu thích nào',
  
  // Messages
  'No categories found.': 'Không tìm thấy danh mục.',
  'No products found.': 'Không tìm thấy sản phẩm.',
  'No reviews found.': 'Không tìm thấy đánh giá.',
  'No orders found.': 'Không tìm thấy đơn hàng.',
  'Order Details': 'Chi tiết đơn hàng',
  'Order Date': 'Ngày đặt hàng',
  'Review Added on': 'Đánh giá được thêm vào',
  'Approved': 'Đã phê duyệt',
  'Rejected': 'Đã từ chối',
  'Waiting Approval': 'Chờ phê duyệt',
  
  // Errors
  'Please Try Again!': 'Vui lòng thử lại!',
  'Unauthorized Access! Please login again': 'Truy cập không được phép! Vui lòng đăng nhập lại',
  'Forbidden! You are not allowed to access this resource.': 'Bị cấm! Bạn không được phép truy cập tài nguyên này.',
  'Your request could not be processed. Please try again.': 'Yêu cầu của bạn không thể xử lý. Vui lòng thử lại.',
  
  // Validation
  'Name is required.': 'Tên là bắt buộc.',
  'Email is required.': 'Email là bắt buộc.',
  'Password is required.': 'Mật khẩu là bắt buộc.',
  'Description is required.': 'Mô tả là bắt buộc.',
  'Products are required.': 'Sản phẩm là bắt buộc.',
  'Description may not be greater than 200 characters.': 'Mô tả không được vượt quá 200 ký tự.',
  
  // Success
  'Subscribe': 'Đăng ký',
  'Add Brand': 'Thêm thương hiệu',
  'Add Category': 'Thêm danh mục',
  'Add Review': 'Thêm đánh giá',
  'Add Product': 'Thêm sản phẩm',
  'Add Merchant': 'Thêm người bán',
  
  // Dashboard
  'Dashboard Menu': 'Menu bảng điều khiển',
  'Account': 'Tài khoản',
  'Logged In With': 'Đăng nhập với',
  'Please Enter Your First Name': 'Vui lòng nhập tên của bạn',
  'Please Enter Your Last Name': 'Vui lòng nhập họ của bạn',
  'Please Enter Your Phone Number': 'Vui lòng nhập số điện thoại của bạn',
  'Save Changes': 'Lưu thay đổi',
  
  // Status
  'Processing': 'Đang xử lý',
  'Shipped': 'Đã gửi hàng',
  'Delivered': 'Đã giao hàng',
  'Cancelled': 'Đã hủy',
  'Not processed': 'Chưa xử lý',
  'You have no orders yet.': 'Bạn không có đơn hàng nào.',
  'Please Enter Your Email': 'Vui lòng nhập email của bạn',
  'Please Enter Your Password': 'Vui lòng nhập mật khẩu của bạn',
  
  // Durian specific
  'Fresh Durian': 'Sầu Riêng Tươi',
  'Frozen Durian': 'Sầu Riêng Đông Lạnh',
  'Processed Durian': 'Sầu Riêng Chế Biến',
  'Ri 6 Durian': 'Sầu Riêng Ri 6',
  'Monthong Durian': 'Sầu Riêng Monthong',
  'Musang King Durian': 'Sầu Riêng Musang King',
  'Ripe': 'Chín',
  'Unripe': 'Chưa chín',
  'Vietnam': 'Việt Nam',
  'Thailand': 'Thái Lan',
  'Malaysia': 'Malaysia',
  'Indonesia': 'Indonesia',
  'kg': 'kg',
  'VNĐ': 'VNĐ'
}; 